services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  server:
    build: ./Server
    restart: unless-stopped
    env_file:
      - ./Server/src/config.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/Flowlist
      - CLIENT_URL=http://localhost:5173
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - app-network

  client:
    build: ./Client
    restart: unless-stopped
    env_file:
      - ./Client/.env
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
